### ISSUE TITLE
External CSS Links not working

### ISSUE THREAD

**Issue by ipc103** [learn-co-curriculum/hs-coding-club-css#1]
The links to Beyonce's stylesheets are no longer working. Beyonce.com has undergone a redesign so we should probably choose a different site to have students style. 

We should probably include the stylesheets in this repo so that we don't have to depend on live links.

**Comment by AnnJohn** [comment]
@ipc103 do you know who's maintaining these lessons? there isn't anyone that i know now that Vic is gone so this issue might stay open for a while.

**Comment by ipc103** [comment]
it actually appears that the links are working again - the 'redesign' of beyonce.com appears to have been temporary.
